from main import Main

if __name__ == '__main__':
    main = Main()
    # trim the end...
    main.trim()
    # back up the server world...
    main.backup()
    # check for any updates...
    main.checkVersion()
    # start critical event monitoring...
    main.startMonitors()
    